### ISSUE TITLE
ruby 3.2 incompatible with Gemfile that includes latest nokogiri

### ISSUE THREAD

**Issue by michaelglass** [kachick/deploy-yard-to-pages#41]
My gemfile has a dependence on nokogiri, and the [latest non-rc nokogiri](https://rubygems.org/gems/nokogiri/versions/1.13.10-x86_64-linux) doesn't support ruby 3.2.

Because of this, the action gets stuck at the `bundle install` phase:

```sh
  Your bundle is locked to nokogiri (1.13.10-x86_64-linux) from rubygems
  repository https://rubygems.org/ or installed locally, but that version can no
  longer be found in that source. That means the author of nokogiri
  (1.13.10-x86_64-linux) has removed it. You'll need to update your bundle to a
  version other than nokogiri (1.13.10-x86_64-linux) that hasn't been removed in
  order to install.
```

Do you have a suggestion for a workaround?

Also: thank you for your wonderful github action! 🤗

**Comment by kachick** [comment]
Thanks for this report! 🙏 I have clarified tagged versions which depends fixed ruby versions as v1.0.0 and v1.1.0.
And since v1.2.0, we can specify the ruby version with ruby-version option.
